bring in hook

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -29,12 +29,7 @@ if [ -n "$remote_name" ] && [ -n "$remote_branch" ]; then
   fi
 fi
 
-# run astro check and tests in parallel; both must pass
-bun run check &
-CHECK_PID=$!
-bun run test
-TEST_EXIT=$?
-wait $CHECK_PID
-CHECK_EXIT=$?
-[ $TEST_EXIT -ne 0 ] || [ $CHECK_EXIT -ne 0 ] && exit 1
+# run astro check first; bail early if it fails
+bun run check || exit 1
+bun run test || exit 1
 exit 0
